[build]
  functions = "functions"  # Вказує на папку, де зберігаються функції
  publish = "public"       # Вказує на папку, де зберігаються статичні файли

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app"
  status = 200
